### ISSUE TITLE
I can add support in IceStudio IDE for ECP5-Mini

### ISSUE THREAD

**Issue by benitoss** [joshajohnson/ecp5-mini#3]
If you want I can add the support in ICeStudio for this board
I have already added support for the  ColorLight ECP5 Boards and ECP5-Evaluation_board. 

https://icestudio.io/

Regards

**Comment by joshajohnson** [comment]
Thanks for the offer @benitoss, support would be great however there are only half a dozen of these boards out in the field so not sure if it would be worth your time. 

I had planned to build / distribute a few boards once I found all the bugs, but don't think I have the time to do that these days.

**Comment by benitoss** [comment]
OK. lets wait you found the bugs and release a definitive version and I will add it in IceStudio.
It is fast , maybe in only one hour is done.
Please Keep me updated in benitoss@gmail.com
Regards

**Comment by benitoss** [comment]
I have already added support to the ECP5-Mini 12K and 25K version r0.2 in IceStudio/Apio
For ICestudio --> https://github.com/FPGAwars/icestudio/pull/560
For Apio (used in IceStudio to synthetize)  --> https://github.com/FPGAwars/apio/pull/257/commits/b3f1ff872154533aa89c5a833d82848d01eae0fc

It is a initial support. HyperRam and USB pins are not added. Maybe in the future we have to add those pins.
The programmer to use is a FT2232H connected to the JTAG of the board.
It is possible to use the DFU programmer but without the board I cannot test it. 

Good luck with your board.
Regards

**Comment by joshajohnson** [comment]
Thanks @benitos!
I'll have a play around with it and see if I can get USB and HyperRAM working over here.
